name: DCChatBubbles
version: '${project.version}'
main: com.diacero.chatbubbles.DCChatBubbles
api-version: "1.20"
description: Muestra los mensajes del chat como globos de texto sobre la cabeza del jugador.
author: DiaCero

commands:
  chatbubble:
    description: Permite apagar o encender las burbujas para ti mismo, o recargar la configuración.
    usage: /chatbubble [reload]
    permission: dc.chatbubble.toggle

permissions:
  dc.chatbubble.toggle:
    description: Permite al jugador desactivar sus propios globos de chat.
    default: true
  dc.chatbubble.reload:
    description: Permite recargar la configuración del plugin.
    default: op
  dc.chatbubble.global:
    description: Permite apagar las burbujas de todo el servidor de emergencia.
    default: op
